apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-summarizer-api-deployment
  labels:
    app: text-summarizer-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-summarizer-api-app
  template:
    metadata:
      labels:
        app: text-summarizer-api-app
    spec:
      containers:
      - name: text-summarizer-api-container
        image: sebastiangau/text-summarizer-api:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: text-summarizer-api-service
spec:
  selector:
    app: text-summarizer-api-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer